import React from 'react';

const Companies = () => {
    return (
        <div className=' my-40 w-9/12 mx-auto'>
            <h1 className=' text-center text-xl font-semibold text-gray-400 mb-10'>
                18,000,000+ images generated by creative companies around the world
            </h1>

            <div className=' flex flex-col md:flex-row justify-between items-center'>
                <img className=' w-6/12 mb-10 md:mb-0 md:w-[7vw]' src="/public/assets/images/the-shoeco.035bbea8.png" alt="" />
                <img className=' w-6/12 mb-10 md:mb-0 md:w-[5vw]' src="/public/assets/images/eva-candles.563b0c5c.png" alt="" />
                <img className=' w-6/12 mb-10 md:mb-0 md:w-[8vw]' src="/public/assets/images/homes-of-rajasthan.bb31e00c.png" alt="" />
                <img className=' w-6/12 mb-10 md:mb-0 md:w-[7vw]' src="/assets/images/enzo-chehab.6f0a9241.png" alt="" />
                <img className=' w-6/12 mb-10 md:mb-0 md:w-[10vw]' src="/assets/images/eleman-beauty.6c6989e5.png" alt="" />
            </div>
        </div>
    );
};

export default Companies;